---
- name: preflight checks
  include_tasks: pre_checks.yml

- name: include family specific tasks
  include_tasks: "{{ ansible_os_family | lower }}.yml"

- name: include common tasks
  include_tasks: common.yml
