---
- name: restart docker
  systemd:
    name: docker
    daemon_reload: yes
    state: restarted

- name: restart containerd
  systemd:
    name: containerd
    daemon_reload: yes
    state: restarted
